<?php
/** @var Psr\Container\ContainerInterface $container */
$container = App::getContainer();

/** @var Mobicms\Api\UserInterface $systemUser */
$systemUser = $container->get(Mobicms\Api\UserInterface::class);

/** @var Mobicms\Api\ToolsInterface $tools */
$tools = $container->get(Mobicms\Api\ToolsInterface::class);
?>
<div class="tmn">
    <a href="<?= $config->homeurl ?>">
        <?= $tools->image('old/menu_home.png') . _t('Home', 'system') ?>
    </a>
    <br>
    <?php if ($systemUser->isValid()): ?>
        <a href="<?= $config->homeurl ?>/profile/?act=office">
            <?= $tools->image('old/menu_cabinet.png') . $systemUser->name ?>
            <small style="color: #a8b5c4">(<?= _t('Personal', 'system') ?>)</small>
        </a>
    <?php else: ?>
        <a href="<?= $config->homeurl ?>/login/">
            <?= $tools->image('old/menu_login.png') . _t('Login', 'system') ?>
        </a>
    <?php endif ?>
</div>
