<?php
/** @var Psr\Container\ContainerInterface $container */
$container = App::getContainer();

/** @var Mobicms\Api\ToolsInterface $tools */
$tools = $container->get(Mobicms\Api\ToolsInterface::class);

$locale = App::getTranslator()->getLocale();
?>
<!DOCTYPE html>
<html lang="<?= $config->lng ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="Generator" content="mobiCMS, https://mobicms.org">
    <meta name="keywords" content="<?= $config->meta_key ?>">
    <meta name="description" content="<?= $config->meta_desc ?>">
    <link rel="stylesheet" href="<?= $config->homeurl ?>/themes/default/assets/css/legacy.css">
    <link rel="shortcut icon" href="<?= $config->homeurl ?>/themes/default/assets/images/favicon.ico">
    <link rel="alternate" type="application/rss+xml" title="RSS | Новости ресурса" href="<?= $config->homeurl ?>/rss/">
    <title><?= (isset($title) ? $this->e($title) . ' | ' : '') . $config->copyright ?></title>
</head>
<body>
<!-- Логотип и переключатель языков -->
<table style="width: 100%;" class="logo">
    <tr>
        <td valign="bottom">
            <a href="<?= $config->homeurl ?>">
                <img src="<?= $this->asset('images/logo.png') ?>" alt="<?= $this->e($config->copyright) ?>" class="icon"/>
            </a>
        </td>
        <?php if (count($config->lng_list) > 1): ?>
            <td align="right">
                <a href="<?= $config->homeurl ?>/language/"><strong><?= strtoupper($locale) ?></strong></a>&#160;
                <a href="<?= $config->homeurl ?>/language/"><?= $tools->getFlag($locale) ?></a>
            </td>
        <?php endif ?>
    </tr>
</table>

<!-- Верхнее меню -->
<?php $this->insert('system::app/old/topmenu') ?>

<div class="maintxt">
    <!-- Уведомления -->
    <?php $this->insert('system::app/old/notifications') ?>

    <!-- Основная информация -->
    <?= $this->section('content') ?>
</div>

<div class="fmenu">
    <!-- Счетчик посетителей онлайн -->
    <img src="<?= $this->asset('images/menu_online.png') ?>" class="icon">
    <a href="<?= $config->homeurl ?>/users/?act=online"><?= $container->get('counters')->online() ?></a>
</div>
<div style="text-align:center">
    <p><?= $this->e($config->copyright) ?></p>
    <!-- Внешние счетчики -->
    <?php $this->insert('system::app/old/counters') ?>
    <div>
        <small>&copy; <a href="https://mobicms.org">mobiCMS</a></small>
    </div>
</div>
</body>
</html>
